name: acerta_palavra_app
description: "Letra a Letra - Um jogo de adivinhar palavras inspirado no Wordle."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# A seção de dependências deve ter esta estrutura
dependencies:
  flutter:
    sdk: flutter
  
  # Cada dependência deve ter dois espaços de indentação
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true

  assets:
    - assets/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"